<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Download the White Paper_optanon-cat_d4ec14</name>
   <tag></tag>
   <elementGuidId>8f35346a-eba4-4290-9ced-57f252ef6bc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.optanon-category-C0002</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@type='text/html']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0c7bb72b-3c3c-4755-b19f-e8ce15328fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>dc93d9a2-ce59-41ab-9846-921ee64637e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>520</value>
      <webElementGuid>1152e293-5028-49cd-b7a8-8e685772cf8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text/html</value>
      <webElementGuid>965e19a6-a989-4a4c-bff7-23c80d101d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d46bb86f-aba2-491c-910e-5f93b3f976da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95ab1f51-1d42-409a-a242-a0fa87f6f0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optanon-category-C0002 </value>
      <webElementGuid>977e851f-e913-43ad-beec-ea9367a63f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www2.kurtosys.com/l/18882/2020-06-04/bx16sd</value>
      <webElementGuid>e3676604-4bb9-4270-ac5a-8da297ccb1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;white-papers-template-default single single-white-papers postid-59806 wp-custom-logo elementor-default elementor-template-full-width elementor-kit-59840 elementor-page elementor-page-59806 elementor-page-2802 kurtosys-desktop-menu-active e--ua-firefox&quot;]/div[@class=&quot;elementor elementor-2802 elementor-location-single post-59806 white-papers type-white-papers status-publish hentry&quot;]/div[@class=&quot;elementor-section-wrap&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-9f7ca53 elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-row&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-5cdccb4&quot;]/div[@class=&quot;elementor-column-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-widget-wrap&quot;]/div[@class=&quot;elementor-element elementor-element-6a96b2a elementor-widget elementor-widget-theme-post-content&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor elementor-59806&quot;]/div[@class=&quot;elementor-inner&quot;]/div[@class=&quot;elementor-section-wrap&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-e2bb756 elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-row&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-90397da&quot;]/div[@class=&quot;elementor-column-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-widget-wrap&quot;]/div[@class=&quot;elementor-element elementor-element-36e05ed elementor-widget elementor-widget-html&quot;]/div[@class=&quot;elementor-widget-container&quot;]/iframe[@class=&quot;optanon-category-C0002&quot;]</value>
      <webElementGuid>203c62dc-c938-4064-ae57-a36aa83c703e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@type='text/html']</value>
      <webElementGuid>4ace0d2f-fee6-4572-85ea-92b785c1deee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fd9e140d-eae1-4ef2-affb-6f1424e0b062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@type = 'text/html' and @src = 'https://www2.kurtosys.com/l/18882/2020-06-04/bx16sd']</value>
      <webElementGuid>0f948699-426c-40f4-88b4-14ca82e37c99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
