<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Insights</name>
   <tag></tag>
   <elementGuidId>59b62d35-08d2-420c-b875-eac9dffc9bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kurtosys-menu-item-75710 > a.top-level-link.menu-image-title-after > div.kurtosys-menu-item-wrapper > div.kurtosys-menu-title > span.menu-image-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='kurtosys-menu-item-75710']/a/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89ee4702-0fd2-4101-8ca6-5a6a04619363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-image-title</value>
      <webElementGuid>e2bef892-f341-4cfd-9fd0-971ff6087f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Insights</value>
      <webElementGuid>dc463a81-47d7-4dbf-ad43-0f817578b2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kurtosys-menu-item-75710&quot;)/a[@class=&quot;top-level-link menu-image-title-after&quot;]/div[@class=&quot;kurtosys-menu-item-wrapper&quot;]/div[@class=&quot;kurtosys-menu-title&quot;]/span[@class=&quot;menu-image-title&quot;]</value>
      <webElementGuid>0f460ca9-c1ce-4eef-a913-5a84720a0ee0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='kurtosys-menu-item-75710']/a/div/div/span</value>
      <webElementGuid>2f1433ef-8634-46f9-8532-89fd155ecfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help center'])[1]/following::span[1]</value>
      <webElementGuid>b0e8d3b9-d47c-4a01-a3e8-6805d7f71ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISOC'])[1]/following::span[2]</value>
      <webElementGuid>7bd1e637-3161-40e2-ad72-990cb2157261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/preceding::span[1]</value>
      <webElementGuid>c5df3db2-2465-46ce-a2f7-9ac62f66c8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Events'])[1]/preceding::span[2]</value>
      <webElementGuid>f251f955-e03d-4bd1-9ec1-cdb2991ae70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Insights']/parent::*</value>
      <webElementGuid>663f5a67-17dd-430f-844e-604583606f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div/div/span</value>
      <webElementGuid>7ff3e015-d929-41a4-92ba-5957af054709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Insights' or . = 'Insights')]</value>
      <webElementGuid>d982ac23-4f6e-4ca0-9abb-15ce176a0eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
